### PR TITLE
Update templates to React 19

### PR DESCRIPTION
**Pull request by brookslybrand**

### CODE REVIEW

**Comment by yoh-000** [comment]
@brookslybrand, the `react-19` branch's default template does not work if you set `ssr: false` in `react-router.config.ts`.  Perhaps not an issue with the template and simply an incompatibility between `react-router` and `react@19`?  `ssr: false` works on `main` branch.

**Comment by SiddharthPant** [comment]
This concerns react-compiler that is introduced with React 19. The below file https://github.com/remix-run/react-router-templates/blob/c1da1b66673c7d0c101a6a249010a8b70b50a67b/node-postgres/tsconfig.node.json#L11 in official templates use `moduleResolution: NodeNext` which causes issues when you try to add react compiler using `vite-react-babel` plugin in `vite.config.ts`. Typescript complains that plugins `babel()` is not a function.
Using `moduleResolution: Bundler` solves this issue.

Here's a working example of changes required to enable react-compiler for RR7: https://github.com/forge42dev/base-stack/pull/20
I was following the same link when I hit the above error and its resolution.

**Comment by brookslybrand** [comment]
Thanks @yoh-000 for pointing that out. Per the last comment you need to set `NODE_ENV=production` when running build

```json
"build": "NODE_ENV=production react-router build"
```

We're looking into if there are better defaults we need to set, but in the meantime this will get you unblocked.

I've updated the appropriate templates to reflect this. I plan to setup a SPA template soon which will have this setup properly by default

**Comment by brookslybrand** [comment]
I'm going to go ahead and merge this. @SiddharthPant please feel free to open up another issue about the "moduleResolution: Bundler" suggestion/issue. It may be something we want to change, but I'm going to let @pcattori or someone else on the team address that

**Comment by brookslybrand** [comment]
@SiddharthPant never mind, I went ahead and updated all remaining tsconfig files in #30

**Pull request merged**
